name: "Run Clippy Linting"
description: "Run cargo clippy with specified feature combinations"

inputs:
  features:
    description: "Feature combinations to test (comma-separated)"
    required: false
    default: "ssl,ssl-rustls,none"
  sarif-output:
    description: "Whether to generate SARIF output"
    required: false
    default: "false"
  sarif-prefix:
    description: "Prefix for SARIF output files"
    required: false
    default: "clippy"

runs:
  using: composite
  steps:
    - name: Run Clippy Linting
      continue-on-error: true
      shell: bash
      run: |
        set -euo pipefail

        # Check for SARIF tools if sarif-output is enabled
        if [[ "${{ inputs.sarif-output }}" == "true" ]]; then
          missing_tools=()

          if ! command -v clippy-sarif >/dev/null 2>&1; then
            missing_tools+=("clippy-sarif")
          fi

          if ! command -v sarif-fmt >/dev/null 2>&1; then
            missing_tools+=("sarif-fmt")
          fi

          if [[ ${#missing_tools[@]} -gt 0 ]]; then
            echo "❌ Error: Required SARIF tools are missing: ${missing_tools[*]}"
            echo "Please ensure clippy-sarif and sarif-fmt are installed and available in PATH"
            exit 1
          fi
        fi

        # Parse features input defensively - handle empty, comma-only, or comma-separated list
        FEATURES=()
        if [[ -n "${{ inputs.features }}" ]]; then
          # Trim the input string
          features_input=$(echo "${{ inputs.features }}" | xargs)
          if [[ -n "$features_input" ]]; then
            # Split by comma and build array with only non-empty trimmed entries
            IFS=',' read -ra raw_features <<< "$features_input"
            for raw_feature in "${raw_features[@]}"; do
              trimmed_feature=$(echo "$raw_feature" | xargs)
              if [[ -n "$trimmed_feature" ]]; then
                FEATURES+=("$trimmed_feature")
              fi
            done
          fi
        fi

        # Early guard: Check if FEATURES array is empty or contains only invalid entries
        if [[ ${#FEATURES[@]} -eq 0 ]]; then
          echo "❌ Error: No valid features specified for clippy linting"
          echo "Available features: ssl, ssl-rustls, none"
          echo "Received features input: '${{ inputs.features }}'"
          exit 1
        fi

        # Lint each feature combination
        processed=0
        for feature in "${FEATURES[@]}"; do
          # Skip empty entries explicitly
          if [[ -z "$feature" ]]; then
            continue
          fi
          case "$feature" in
            "ssl")
              echo "🔍 Running clippy with ssl feature..."
              if [[ "${{ inputs.sarif-output }}" == "true" ]]; then
                cargo clippy --all-targets --no-default-features --features "json csv ssl additional_mysql_types verbose" --message-format=json -- -D warnings \
                  | clippy-sarif \
                  | tee "${{ inputs.sarif-prefix }}-ssl.sarif" \
                  | sarif-fmt
              else
                # Stream output to both console and error log, preserve exit code
                cargo clippy --all-targets --no-default-features --features "json csv ssl additional_mysql_types verbose" -- -D warnings 2>&1 | tee /tmp/clippy_error.log
                clippy_exit_code=${PIPESTATUS[0]}
                if [[ $clippy_exit_code -ne 0 ]]; then
                  echo "❌ Clippy failed with ssl features (exit code: $clippy_exit_code):"
                  cat /tmp/clippy_error.log
                  exit $clippy_exit_code
                fi
              fi
              ((processed++))
              ;;
            "ssl-rustls")
              echo "🔍 Running clippy with ssl-rustls feature..."
              if [[ "${{ inputs.sarif-output }}" == "true" ]]; then
                cargo clippy --all-targets --no-default-features --features "json csv ssl-rustls additional_mysql_types verbose" --message-format=json -- -D warnings \
                  | clippy-sarif \
                  | tee "${{ inputs.sarif-prefix }}-ssl-rustls.sarif" \
                  | sarif-fmt
              else
                # Stream output to both console and error log, preserve exit code
                cargo clippy --all-targets --no-default-features --features "json csv ssl-rustls additional_mysql_types verbose" -- -D warnings 2>&1 | tee /tmp/clippy_error.log
                clippy_exit_code=${PIPESTATUS[0]}
                if [[ $clippy_exit_code -ne 0 ]]; then
                  echo "❌ Clippy failed with ssl-rustls features (exit code: $clippy_exit_code):"
                  cat /tmp/clippy_error.log
                  exit $clippy_exit_code
                fi
              fi
              ((processed++))
              ;;
            "none")
              echo "🔍 Running clippy without TLS features..."
              if [[ "${{ inputs.sarif-output }}" == "true" ]]; then
                cargo clippy --all-targets --no-default-features --features "json csv additional_mysql_types verbose" --message-format=json -- -D warnings \
                  | clippy-sarif \
                  | tee "${{ inputs.sarif-prefix }}-notls.sarif" \
                  | sarif-fmt
              else
                # Stream output to both console and error log, preserve exit code
                cargo clippy --all-targets --no-default-features --features "json csv additional_mysql_types verbose" -- -D warnings 2>&1 | tee /tmp/clippy_error.log
                clippy_exit_code=${PIPESTATUS[0]}
                if [[ $clippy_exit_code -ne 0 ]]; then
                  echo "❌ Clippy failed without TLS features (exit code: $clippy_exit_code):"
                  cat /tmp/clippy_error.log
                  exit $clippy_exit_code
                fi
              fi
              ((processed++))
              ;;
            *)
              echo "⚠️ Unknown feature: $feature, skipping..."
              ;;
          esac
        done

        # Check if any features were actually processed
        if [[ $processed -eq 0 ]]; then
          echo "❌ Error: No valid features were processed during clippy linting"
          echo "Available features: ssl, ssl-rustls, none"
          echo "Received features: ${FEATURES[*]}"
          exit 1
        fi

        # Print success message only if we reach this point (processed > 0)
        echo "✅ Clippy linting completed successfully"
