name: "Setup Rust Environment"
description: "Setup Rust toolchain with common components and caching"

inputs:
  components:
    description: "Rust components to install (comma-separated)"
    required: false
    default: "clippy,rustfmt"
  install-cargo-audit:
    description: "Whether to install cargo-audit"
    required: false
    default: "false"
  install-nextest:
    description: "Whether to install nextest"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install Rust (stable)
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}

    - name: Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Install nextest
      if: inputs.install-nextest == 'true'
      uses: taiki-e/install-action@v2
      with:
        tool: nextest

    - name: Install cargo-audit
      if: inputs.install-cargo-audit == 'true'
      shell: bash
      run: |
        cargo +stable install cargo-audit --version 0.21.2 --locked
