rules:
  template-injection:
    ignore:
      - release.yml
  excessive-permissions:
    ignore:
      - release.yml
      - docs.yml
      - ci.yml
  unpinned-uses:
    ignore:
      - release.yml
      - cargo-dist.yml
      - ci.yml
      - codeql.yml
      - docs.yml
      - security.yml
