block-list-secret-scan: []
branch: master
custom-tool-name: Checkov
directory:
  - .
evaluate-variables: true
external-modules-download-path: .external_modules
hard-fail-on:
  - MEDIUM
mask: []
output:
  - github_failed_only
quiet: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_DOCKER_2
soft-fail-on:
  - LOW
summary-position: top
use-enforcement-rules: true
