# Exclude patterns not supported in python earlier than 3.13
exclude = [
    "venv/**",
    "**/node_modules/**",
    "**/*.txt",
    "**/*.mdc",
    "**/*.tpl.md",
    "**/CHANGELOG.md",
    "rust_migration/index.md",
]
validate = true
number = true

[plugin.mkdocs]
align_semantic_breaks_in_lists = true
ignore_missing_references = true
