# mdformat configuration - consistent with Prettier and markdownlint
exclude = [
    "venv/**",
    "**/node_modules/**",
    "**/*.txt",
    "**/*.mdc",
    "**/*.tpl.md",
    "**/CHANGELOG.md",
    "docs/src/SUMMARY.md",
    "docs/src/usage/output-formats.md",
    "rust_migration/index.md",
]
validate = true
number = true
wrap = 100  # Consistent with Prettier's printWidth
end_of_line = "lf"
extensions = [
    "gfm",
    "frontmatter",
    "footnote",
    "simple_breaks",
    "tables",
    "gfm_alerts",
    "toc",
    "wikilink",
]

[plugin.mkdocs]
align_semantic_breaks_in_lists = true
ignore_missing_references = true
