[package]
name = "gold_digger"
version = "0.1.2"
edition = "2021"

[dependencies]
mysql = { version = "22.2" }
anyhow = "1.0"
csv = "1.1"
openssl-sys = "0.9.75"

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'
debug = false
debug-assertions = false
strip = true
panic = "abort"

[features]
default = ["vendored"]
vendored = ["openssl-sys/vendored"]
