[package]
name = "gold_digger"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = { version = "22.0" }
anyhow = "1.0"
csv = "1.1"

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'
debug = false
debug-assertions = false
