[package]
name = "gold_digger"
version = "0.1.2"
edition = "2021"
authors = ["UncleSp1d3r <unclespider@protonmail.com>"]
description = "A simple MySQL/MariaDB query tool that accepts parameters as environmental variables."
readme = "README.md"
repository = "https://github.com/unclesp1d3r/gold_digger"
license = "MIT"
keywords = ["mysql", "query", "tool", "mariadb"]
categories = ["command-line-utilities"]
exclude = [".github/"]


[dependencies]
mysql = { version = "23.0.1" }
anyhow = "1.0.61"
csv = "1.1.6"
openssl-sys = "0.9.75"

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'
debug = false
debug-assertions = false
strip = true
panic = "abort"

[features]
default = ["vendored"]
vendored = ["openssl-sys/vendored"]
