coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 70%
        threshold: 5%
  ignore:
    - "tests/**/*"
    - "benches/**/*"
    - "examples/**/*"
    - "target/**/*"
