[tools]
cargo-binstall              = "latest"
cargo-insta                 = "1.47.2"
"cargo:cargo-audit"         = "0.22.1"
"cargo:cargo-deny"          = "0.19.4"
"cargo:git-cliff"           = "latest"
"cargo:cargo-dist"          = "0.31.0"
"cargo:cargo-llvm-cov"      = "0.8.5"
"cargo:cargo-nextest"       = "0.9.133"
"cargo:mdbook"              = "0.5.2"
"cargo:mdbook-linkcheck"    = "0.7.7"
"cargo:mdbook-tabs"         = "0.3.4"
"cargo:mdbook-mermaid"      = "0.17.0"
"cargo:mdbook-toc"          = "0.15.3"
"cargo:mdbook-admonish"     = "1.20.0"
"cargo:mdbook-open-on-gh"   = "3.0.0"
"cargo:mdbook-i18n-helpers" = "0.4.0"
just                        = "latest"
python                      = "latest"
rust                        = { version = "stable", components = "llvm-tools,cargo,rustfmt,clippy", profile = "default" }
"cargo:cargo-outdated"      = "0.19.0"
"cargo:cargo-release"       = "1.1.2"
"cargo:cargo-auditable"     = "0.7.4"
"cargo:cargo-cyclonedx"     = "0.5.9"
"pipx:mdformat"             = { version = "1.0.0", uvx_args = "--with mdformat-gfm --with mdformat-front-matters --with mdformat-footnote --with mdformat-simple-breaks --with mdformat-gfm-alerts --with mdformat-toc --with mdformat-wikilink --with mdformat-tables" }
prettier                    = "latest"
actionlint                  = "latest"
lychee                      = "0.23.0"
markdownlint-cli2           = "0.22.1"
"cargo:cargo-watch"         = "8.5.3"
grype                       = "latest"
syft                        = "latest"
act                         = { version = "0.2.87", os = ["linux", "macos"] }
"pipx:sqlfluff"             = "4.1.0"
docker-compose              = "latest"
docker-cli                  = "latest"
"pipx:pre-commit"           = "latest"
oxlint                      = "latest"
ruff                        = "latest"
shellcheck                  = "latest"
bun                         = "latest"

# Many of these settings are defaults, but we are explicit in case they change in the future and to make it clear to users what is enabled.
[settings]
activate_aggressive                 = true
idiomatic_version_file_enable_tools = [ "python", "rust", "bun" ]
env_cache                           = true
exec_auto_install                   = true
github_attestations                 = true
lockfile                            = true
slsa                                = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true
