style: github
template: CHANGELOG.tpl.md
info:
    title: CHANGELOG
    repository_url: https://github.com/unclesp1d3r/gold_digger
options:
    commits:
        filters:
            Type:
                - feat
                - fix
                - perf
                - refactor
                - docs
                - test
                - chore
                - ci
                - style
    commit_groups:
        title_maps:
            feat: Features
            fix: Bug Fixes
            perf: Performance Improvements
            refactor: Code Refactoring
            docs: Documentation Update
            test: Test Improvements
            chore: Maintenance
            ci: Continuous Integration
            style: Style
    header:
        pattern: "^(\\w*)\\:\\s(.*)$"
        pattern_maps:
            - Type
            - Subject
    notes:
        keywords:
            - BREAKING CHANGE
