[book]
authors = ["UncleSp1d3r"]
language = "en"
multilingual = false
src = "src"
title = "Gold Digger Documentation"
description = "MySQL/MariaDB query tool with structured output"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/UncleSp1d3r/gold_digger"
edit-url-template = "https://github.com/UncleSp1d3r/gold_digger/edit/main/docs/src/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 1

[output.html.playground]
runnable = false

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.0"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.linkcheck]
command = "mdbook-linkcheck"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"

[preprocessor.tabs]
command = "mdbook-tabs"

[preprocessor.i18n-helpers]
command = "mdbook-i18n-helpers"
