name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-22.04
    concurrency:
      group: ci-${{ github.ref }}-ubuntu-validation
      cancel-in-progress: true

    env:
      PRE_COMMIT_HOME: ${{ github.workspace }}/.cache/pre-commit

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust
        with:
          components: "clippy,rustfmt"
          install-cargo-audit: "true"
          install-nextest: "true"

      - name: Install just
        uses: extractions/setup-just@v3

      # Build dependencies first to avoid compilation issues during linting
      - name: Build project dependencies
        uses: ./.github/actions/build-dependencies
        with:
          features: "native-tls"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pre-commit
        shell: bash
        run: python -m pip install pre-commit

      - name: Create pre-commit cache directory
        shell: bash
        run: mkdir -p "$PRE_COMMIT_HOME"

      - name: Pre-commit cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PRE_COMMIT_HOME }}
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Pre-commit validation
        shell: bash
        run: pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Format check
        shell: bash
        run: just fmt-check

      - name: Lint check
        uses: ./.github/actions/run-clippy
        with:
          features: "native-tls"
          sarif-output: "false"

      # Run a quick test to ensure basic functionality works for validation
      - name: Quick validation test
        uses: ./.github/actions/run-tests
        with:
          features: "native-tls"
          use-nextest: "true"
