name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        tls: [native-tls, rustls]
        include:
          # Test minimal build (no TLS) on Ubuntu only to avoid redundancy
          - os: ubuntu-22.04
            tls: none
      fail-fast: false
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ci-${{ github.ref }}-${{ matrix.os }}-${{ matrix.tls }}
      cancel-in-progress: true

    env:
      PRE_COMMIT_HOME: ${{ github.workspace }}/.cache/pre-commit

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # No longer needed: Windows OpenSSL setup removed for rustls migration

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      # Build dependencies first to avoid compilation issues during linting
      - name: Build project dependencies
        shell: bash
        run: |
          case "${{ matrix.tls }}" in
            "native-tls")
              echo "🔨 Building with native-tls (ssl feature)..."
              cargo check --all-targets --no-default-features --features "json csv ssl additional_mysql_types verbose"
              ;;
            "rustls")
              echo "🔨 Building with rustls (ssl-rustls feature)..."
              cargo check --all-targets --no-default-features --features "json csv ssl-rustls additional_mysql_types verbose"
              ;;
            "none")
              echo "🔨 Building without TLS features..."
              cargo check --all-targets --no-default-features --features "json csv additional_mysql_types verbose"
              ;;
          esac

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pre-commit
        shell: bash
        run: python -m pip install pre-commit

      - name: Create pre-commit cache directory
        shell: bash
        run: mkdir -p "$PRE_COMMIT_HOME"

      - name: Pre-commit cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PRE_COMMIT_HOME }}
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Pre-commit validation
        shell: bash
        run: pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Format check
        shell: bash
        run: just fmt-check

      - name: Lint check
        shell: bash
        run: |
          case "${{ matrix.tls }}" in
            "native-tls")
              echo "🔍 Linting with native-tls (ssl feature)..."
              cargo clippy --all-targets --no-default-features --features "json csv ssl additional_mysql_types verbose" -- -D warnings
              ;;
            "rustls")
              echo "🔍 Linting with rustls (ssl-rustls feature)..."
              cargo clippy --all-targets --no-default-features --features "json csv ssl-rustls additional_mysql_types verbose" -- -D warnings
              ;;
            "none")
              echo "🔍 Linting without TLS features..."
              cargo clippy --all-targets --no-default-features --features "json csv additional_mysql_types verbose" -- -D warnings
              ;;
          esac

      - name: Tests (nextest)
        shell: bash
        run: |
          case "${{ matrix.tls }}" in
            "native-tls")
              echo "🧪 Testing with native-tls (ssl feature)..."
              cargo nextest run --no-default-features --features "json csv ssl additional_mysql_types verbose" || cargo test --no-default-features --features "json csv ssl additional_mysql_types verbose"
              ;;
            "rustls")
              echo "🧪 Testing with rustls (ssl-rustls feature)..."
              cargo nextest run --no-default-features --features "json csv ssl-rustls additional_mysql_types verbose" || cargo test --no-default-features --features "json csv ssl-rustls additional_mysql_types verbose"
              ;;
            "none")
              echo "🧪 Testing without TLS features..."
              cargo nextest run --no-default-features --features "json csv additional_mysql_types verbose" || cargo test --no-default-features --features "json csv additional_mysql_types verbose"
              ;;
          esac

      # Dependency tree validation for TLS migration
      - name: Dependency tree validation
        shell: bash
        run: |
          echo "🔍 Validating dependency tree for TLS configuration: ${{ matrix.tls }}"

          case "${{ matrix.tls }}" in
            "native-tls")
              echo "Testing ssl feature (native-tls)..."
              cargo tree --no-default-features --features ssl -f "{p} {f}" > deps.txt
              if ! grep -q "native-tls" deps.txt; then
                echo "❌ ERROR: native-tls not found with ssl feature"
                cat deps.txt
                exit 1
              fi
              echo "✅ ssl feature validation passed"
              ;;
            "rustls")
              echo "Testing ssl-rustls feature (rustls)..."
              cargo tree --no-default-features --features ssl-rustls -f "{p} {f}" > deps.txt
              if grep -q "native-tls" deps.txt; then
                echo "❌ ERROR: native-tls found with ssl-rustls feature"
                cat deps.txt
                exit 1
              fi
              if ! grep -q "rustls" deps.txt; then
                echo "❌ ERROR: rustls not found with ssl-rustls feature"
                cat deps.txt
                exit 1
              fi
              echo "✅ ssl-rustls feature validation passed"
              ;;
            "none")
              echo "Testing no TLS features..."
              cargo tree --no-default-features --features json,csv -f "{p} {f}" > deps.txt
              if grep -q "native-tls\|rustls" deps.txt; then
                echo "❌ ERROR: TLS dependencies found without TLS features"
                cat deps.txt
                exit 1
              fi
              echo "✅ no TLS features validation passed"
              ;;
          esac

          echo "🎉 Dependency validation passed for ${{ matrix.tls }}!"

      # Build time comparison metrics collection
      - name: Build time comparison
        shell: bash
        run: |
          echo "⏱️ Collecting build time metrics for ${{ matrix.tls }} on ${{ matrix.os }}"

          # Clean previous builds
          cargo clean

          # Time the build
          start_time=$(date +%s)
          case "${{ matrix.tls }}" in
            "native-tls")
              echo "Building with native-tls..."
              cargo build --release --no-default-features --features "json csv ssl additional_mysql_types verbose"
              ;;
            "rustls")
              echo "Building with rustls..."
              cargo build --release --no-default-features --features "json csv ssl-rustls additional_mysql_types verbose"
              ;;
            "none")
              echo "Building without TLS..."
              cargo build --release --no-default-features --features "json csv additional_mysql_types verbose"
              ;;
          esac
          end_time=$(date +%s)

          build_time=$((end_time - start_time))
          echo "🏁 Build completed in ${build_time} seconds"

          # Get binary size
          if [[ "${{ matrix.os }}" == "windows-2022" ]]; then
            binary_path="target/release/gold_digger.exe"
          else
            binary_path="target/release/gold_digger"
          fi

          if [[ -f "$binary_path" ]]; then
            binary_size=$(stat -c%s "$binary_path" 2>/dev/null || stat -f%z "$binary_path" 2>/dev/null || echo "unknown")
            echo "📦 Binary size: ${binary_size} bytes"
          else
            echo "⚠️ Binary not found at expected path: $binary_path"
          fi

          # Create metrics summary
          echo "📊 Build Metrics Summary:"
          echo "  OS: ${{ matrix.os }}"
          echo "  TLS: ${{ matrix.tls }}"
          echo "  Build Time: ${build_time}s"
          echo "  Binary Size: ${binary_size} bytes"

          # Save metrics to file for potential artifact upload
          mkdir -p build-metrics
          cat > "build-metrics/metrics-${{ matrix.os }}-${{ matrix.tls }}.txt" << EOF
          os=${{ matrix.os }}
          tls=${{ matrix.tls }}
          build_time=${build_time}
          binary_size=${binary_size}
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          EOF

      - name: Upload build metrics
        uses: actions/upload-artifact@v4
        with:
          name: build-metrics-${{ matrix.os }}-${{ matrix.tls }}
          path: build-metrics/
          retention-days: 30

      # Coverage - only run on Ubuntu with native-tls to avoid redundancy
      - name: Install cargo-llvm-cov
        if: matrix.os == 'ubuntu-22.04' && matrix.tls == 'native-tls'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Coverage (llvm-cov)
        if: matrix.os == 'ubuntu-22.04' && matrix.tls == 'native-tls'
        shell: bash
        run: |
          echo "📊 Running coverage with native-tls configuration..."
          cargo llvm-cov --workspace --lcov --output-path lcov.info --no-default-features --features "json csv ssl additional_mysql_types verbose"

      - name: Upload coverage artifact
        if: matrix.os == 'ubuntu-22.04' && matrix.tls == 'native-tls'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: lcov.info

      - name: Upload to Codecov
        if: matrix.os == 'ubuntu-22.04' && matrix.tls == 'native-tls' && github.repository == 'UncleSp1d3r/gold_digger'
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          flags: unit
          fail_ci_if_error: false
          verbose: true
