name: Cross-Platform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            features: ssl
          - os: ubuntu-latest
            features: ssl-rustls
          - os: macos-latest
            features: ssl
          - os: windows-latest
            features: ssl
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests and build
        shell: bash
        run: |
          if [ "${{ matrix.features }}" = "none" ]; then
            cargo test --no-default-features --features "json csv additional_mysql_types verbose"
            cargo build --release --no-default-features --features "json csv additional_mysql_types verbose"
          else
            cargo test --no-default-features --features "json csv ${{ matrix.features }} additional_mysql_types verbose"
            cargo build --release --no-default-features --features "json csv ${{ matrix.features }} additional_mysql_types verbose"
          fi
