name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run security checks
        run: |
          cargo audit
          cargo deny check
          cargo binstall cargo-outdated --no-confirm && cargo outdated
