name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  security-scan:
    name: Static & Supply Chain Security
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install SARIF tools
        run: cargo +stable install clippy-sarif sarif-fmt

      - name: Clippy to SARIF (no warnings tolerated)
        run: |
          set -o pipefail
          cargo clippy --all-targets --all-features -D warnings --message-format=json \
            | clippy-sarif \
            | tee clippy.sarif \
            | sarif-fmt

      - name: Upload clippy SARIF
        if: github.event.pull_request == null || github.event.pull_request.head.repo.full_name == github.repository
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: clippy.sarif

      - name: Install syft and grype
        shell: bash
        run: |
          # Install syft
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin

          # Install grype
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Generate SBOM (CycloneDX)
        run: |
          syft . -o cyclonedx-json=sbom.cdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: sbom.cdx.json

      - name: Vulnerability scan with grype
        run: |
          grype sbom.cdx.json --fail-on high --output sarif --file results.sarif

      - name: Upload grype SARIF
        if: github.event.pull_request == null || github.event.pull_request.head.repo.full_name == github.repository
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Cache cargo bin
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-

      - name: Install cargo-audit
        run: |
          cargo +stable install cargo-audit --version 0.21.2 --locked

      - name: cargo-audit
        run: cargo +stable audit

      - name: Install cargo-deny
        run: |
          cargo +stable install cargo-deny --version 0.18.4 --locked

      - name: cargo-deny
        run: cargo +stable deny check
