name: TLS Integration Tests

on:
  push:
    branches: [main]
    paths:
      - "src/tls.rs"
      - "tests/tls_*.rs"
      - "Cargo.toml"
  pull_request:
    branches: [main]
    paths:
      - "src/tls.rs"
      - "tests/tls_*.rs"
      - "Cargo.toml"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CI: true

jobs:
  # Test TLS functionality across platforms (always available)
  tls-cross-platform:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - uses: Swatinem/rust-cache@v2

      - name: Run TLS tests (always available)
        run: cargo nextest run -E 'test(tls)'

      - name: Verify TLS dependencies (rustls-only)
        run: |
          # Should have rustls dependencies (always available)
          cargo tree | grep rustls
          # Should NOT have native-tls (rustls-only implementation)
          ! cargo tree | grep "native-tls"

      - name: Test TLS with minimal features
        run: |
          # TLS should be available even with minimal features
          cargo build --no-default-features --features "json csv"
          cargo tree --no-default-features --features "json csv" | grep rustls

  # Test TLS CLI integration (always available)
  tls-cli-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Build and test TLS CLI (always available)
        run: |
          cargo build --release

          # Set up binary path with Windows .exe suffix detection
          BIN="./target/release/gold_digger"
          if [ -f "${BIN}.exe" ]; then
            BIN="${BIN}.exe"
          fi

          # Test help includes TLS flags (always available)
          "$BIN" --help | grep -E "(tls-ca-file|insecure-skip-hostname-verify|allow-invalid-certificate)" \
            || exit 1

          # Test mutual exclusion (should fail)
          echo "test" > /tmp/test.pem
          ! "$BIN" --tls-ca-file /tmp/test.pem --insecure-skip-hostname-verify \
            --db-url "mysql://test" --query "SELECT 1" --output /tmp/test.json 2>/dev/null

      - name: Test TLS CLI with minimal build
        run: |
          # Build with minimal features and verify TLS CLI is still available
          cargo build --release --no-default-features --features "json csv"

          # Set up binary path with Windows .exe suffix detection
          BIN="./target/release/gold_digger"
          if [ -f "${BIN}.exe" ]; then
            BIN="${BIN}.exe"
          fi

          # Test help includes TLS flags even with minimal features
          "$BIN" --help | grep -E "(tls-ca-file|insecure-skip-hostname-verify|allow-invalid-certificate)" \
            || exit 1
